boj_url = 'https://www.acmicpc.net'
login_path = '/login'
user_path = '/user/'
git_url = 'https://api.github.com'

boj_tier = {
    -1: 'Extra',
    0: 'Unrated',
    1: 'Bronze V',
    2: 'Bronze IV',
    3: 'Bronze III',
    4: 'Bronze II',
    5: 'Bronze I',
    6: 'Silver V',
    7: 'Silver IV',
    8: 'Silver III',
    9: 'Silver II',
    10: 'Silver I',
    11: 'Gold V',
    12: 'Gold IV',
    13: 'Gold III',
    14: 'Gold II',
    15: 'Gold I',
    16: 'Platinum V',
    17: 'Platinum IV',
    18: 'Platinum III',
    19: 'Platinum II',
    20: 'Platinum I',
    21: 'Diamond V',
    22: 'Diamond IV',
    23: 'Diamond III',
    24: 'Diamond II',
    25: 'Diamond I',
    26: 'Ruby V',
    27: 'Ruby IV',
    28: 'Ruby III',
    29: 'Ruby II',
    30: 'Ruby I',
    31: 'Master',
}

languages = {
    'Java': 'java',
    'Java 8': 'java',
    'Java 8 (OpenJDK)': 'java',
    'Java 11': 'java',
    'Java 15': 'java',
    'C': 'c',
    'C99': 'c',
    'C90': 'c',
    'C11': 'c',
    'C2x': 'c',
    'C90 (Clang)': 'c',
    'C99 (Clang)': 'c',
    'C11 (Clang)': 'c',
    'C2x (Clang)': 'c',
    'C++': 'cc',
    'C++98': 'cc',
    'C++11': 'cc',
    'C++17': 'cc',
    'C++20': 'cc',
    'C++14': 'cc',
    'C++98 (Clang)': 'cc',
    'C++11 (Clang)': 'cc',
    'C++14 (Clang)': 'cc',
    'C++17 (Clang)': 'cc',
    'C++20 (Clang)': 'cc',
    'C#': 'cs',
    'C# 3.0 (Mono)': 'cs',
    'C# 6.0 (Mono)': 'cs',
    'C# 9.0 (.NET)': 'cs',
    'D': 'd',
    'D (LDC)': 'd',
    'F#': 'fs',
    'F# (Mono)': 'fs',
    'F# (.NET)': 'fs',
    'Objective-C': 'm',
    'Objective-C++': 'mm',
    'Python': 'py',
    'Python 2': 'py',
    'Python 3': 'py',
    'PyPy': 'py',
    'PyPy2': 'py',
    'PyPy3': 'py',
    'Ruby': 'rb',
    'Ruby 1.8': 'rb',
    'Ruby 1.9': 'rb',
    'Ruby 2': 'rb',
    'Kotlin': 'kt',
    'Kotlin (JVM)': 'kt',
    'Kotlin (Native)': 'kt',
    'Visual Basic': 'vb',
    'Visual Basic (.NET)': 'vb',
    'VB.NET 2.0 (Mono)': 'vb',
    'VB.NET 4.0 (Mono)': 'vb',
    'PHP': 'php',
    'Assembly': 'o',
    'Assembly (32bit)': 'o',
    'Assembly (64bit)': 'o',
    'Rust': 'rs',
    'Rust 2015': 'rs',
    'Rust 2018': 'rs',
    'Rust 2019': 'rs',
    'Swift': 'swift',
    'Go': 'go',
    'Go (gccgo)': 'go',
    'Text': 'txt',
    'node.js': 'js',
    'TypeScript': 'ts',
    'Pascal': 'pas',
    'Lua': 'lua',
    'Perl': 'pl',
    'Bash': 'sh',
    'awk': 'awk',
    'bc': 'bc',
    'sed': 'sed',
    'Haskell': 'hs',
    'Fortran': 'f95',
    'Cobol': 'cob',
    'Algol 68': 'a68',
    'Golfscript': 'gs',
    'Cobra': 'cobra',
    'Befunge': 'bf',
    'Haxe': 'hx',
    'LOLCODE': 'lol',
    'Scheme': 'scm',
    'Ada': 'ada',
    'OCaml': 'ml',
    'Brainf**k': 'bf',
    'Whitespace': 'ws',
    'Tcl': 'tcl',
    'Rhino': 'js',
    'Pike': 'pike',
    'Boo': 'boo',
    'INTERCAL': 'i',
    'Nemerle': 'n',
    'Nimrod': 'nim',
    'FreeBASIC': 'bas',
    'Coq': 'v',
    'Minecraft': 'mca',
    'SystemVerilog': 'sv',
    'APECODE': 'ape',
    'Crystal': 'cr',
    '아희': 'aheui',
    '엄준식': 'umm'
}
